### ISSUE TITLE
doesn't work for me on 3.9

### ISSUE THREAD

**Issue by hzied** [kahunalu/pwnbin#14]
Crawling http://pastebin.com Press ctrl+c to save file to log.txt
Traceback (most recent call last):
  File "C:\Users\zied_\Desktop\pwnbin-master\pwnbin.py", line 27, in main
    root_html = BeautifulSoup(fetch_page(root_url), 'html.parser')
  File "C:\Users\zied_\Desktop\pwnbin-master\pwnbin.py", line 131, in fetch_page
    response = urllib.request.urlopen(page)
AttributeError: module 'urllib' has no attribute 'request'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\zied_\Desktop\pwnbin-master\pwnbin.py", line 187, in <module>
    main(sys.argv[1:])
  File "C:\Users\zied_\Desktop\pwnbin-master\pwnbin.py", line 77, in main
    except urllib.error.HTTPError as err:
AttributeError: module 'urllib' has no attribute 'error'

**Comment by gstone787** [comment]
> Crawling http://pastebin.com Press ctrl+c to save file to log.txt
> Traceback (most recent call last):
> File "C:\Users\zied_\Desktop\pwnbin-master\pwnbin.py", line 27, in main
> root_html = BeautifulSoup(fetch_page(root_url), 'html.parser')
> File "C:\Users\zied_\Desktop\pwnbin-master\pwnbin.py", line 131, in fetch_page
> response = urllib.request.urlopen(page)
> AttributeError: module 'urllib' has no attribute 'request'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "C:\Users\zied_\Desktop\pwnbin-master\pwnbin.py", line 187, in
> main(sys.argv[1:])
> File "C:\Users\zied_\Desktop\pwnbin-master\pwnbin.py", line 77, in main
> except urllib.error.HTTPError as err:
> AttributeError: module 'urllib' has no attribute 'error'

Same here

**Comment by kalistamp** [comment]
me as well

**Comment by kegearda** [comment]
I have solved that by changing the import from urllib to urllib.request and urllib.error  
but now i get this error 

`Crawling http://pastebin.com Press ctrl+c to save file to log.txt
Traceback (most recent call last):
  File "/home/kali/pwnbin/pwnbin.py", line 188, in <module>
    main(sys.argv[1:])
  File "/home/kali/pwnbin/pwnbin.py", line 31, in main
    for paste in find_new_pastes(root_html):
  File "/home/kali/pwnbin/pwnbin.py", line 115, in find_new_pastes
    for li in ul.findChildren():
AttributeError: 'NoneType' object has no attribute 'findChildren'`
