### ISSUE TITLE
crawling pastebin for specific keyword

### ISSUE THREAD

**Issue by totoroha** [kahunalu/pwnbin#6]
Dear Luke,

I'm trying to use your script to look for some keywords on pastebin. This is the command that i use from my Kali box:
python pwnbin.py -k pass "malware". But i got this error instead:
---------------------
Traceback (most recent call last):
  File "pwnbin.py", line 5, in <module>
    from bs4 import BeautifulSoup
  File "/home/kali/.local/lib/python2.7/site-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/home/kali/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 311, in <module>
    from . import _html5lib
  File "/home/kali/.local/lib/python2.7/site-packages/bs4/builder/_html5lib.py", line 57, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'
-----------------------
Can you tell me where i did wrong?

Thank you so much for your help!

**Comment by Retro64XYZ** [comment]
You don't have beautifulSoup installed correctly. This is a python2 module and you appear to be using python3.


Do -

`pip install bs4`
